# Generated by Django 3.1.3 on 2020-11-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20201121_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
