# Generated by Django 3.1.3 on 2020-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('F', 'Fiction'), ('N', 'Novel'), ('NF', 'Non-fiction'), ('M', 'Mystery'), ('HF', 'Historical-fiction'), ('P', 'Poetry'), ('B', 'Biography'), ('CL', 'Children-literature'), ('A', 'Autobiography'), ('P', 'Philosophy'), ('SH', 'Self-help')], max_length=2),
        ),
    ]
